# Generated by Django 3.1.7 on 2021-03-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recursos',
            new_name='Recurso',
        ),
    ]
